import type { ClothingItem } from './types';

export const clothingItems: ClothingItem[] = [
  {
    id: 'dayak',
    name: 'Baju Adat Dayak',
    origin: 'Kalimantan',
    description: 'Pakaian adat Suku Dayak, kaya akan motif alam dan manik-manik yang melambangkan status dan keberanian.',
    imageUrl: '/assets/wastra-dayak.png',
    coordinates: { lat: -0.5, lng: 114.0 },
  },
  {
    id: 'minangkabau',
    name: 'Bundo Kanduang',
    origin: 'Sumatera Barat',
    description: 'Pakaian adat Minangkabau yang megah, melambangkan peran penting perempuan dalam adat matrilineal.',
    imageUrl: '/assets/wastra-minang.png',
    coordinates: { lat: -0.94, lng: 100.36 },
  },
  {
    id: 'bugis',
    name: 'Baju Bodo',
    origin: 'Sulawesi Selatan',
    description: 'Salah satu busana tertua di dunia, Baju Bodo dari Suku Bugis-Makassar memiliki warna yang menandakan usia dan status.',
    imageUrl: '/assets/wastra-bugis.png',
    coordinates: { lat: -4.5, lng: 120.0 },
  },
  {
    id: 'bali',
    name: 'Payas Agung',
    origin: 'Bali',
    description: 'Busana adat Bali yang mewah dan agung, biasanya dikenakan saat upacara pernikahan atau potong gigi.',
    imageUrl: '/assets/wastra-bali.png',
    coordinates: { lat: -8.4, lng: 115.18 },
  },
  {
    id: 'batak',
    name: 'Ulos Batak',
    origin: 'Sumatera Utara',
    description: 'Kain tenun Ulos yang menjadi simbol restu, kasih sayang, dan persatuan dalam masyarakat Batak.',
    imageUrl: '/assets/wastra-batak.png',
    coordinates: { lat: 2.5, lng: 99.0 },
  },
  {
    id: 'jawa',
    name: 'Kebaya Jawa',
    origin: 'Jawa Tengah',
    description: 'Kebaya Jawa adalah busana anggun yang mencerminkan filosofi kesederhanaan dan kelembutan wanita Jawa.',
    imageUrl: '/assets/wastra-jawa.png',
    coordinates: { lat: -7.15, lng: 110.14 },
  },
  {
    id: 'betawi',
    name: 'Pangsi Betawi',
    origin: 'DKI Jakarta',
    description: 'Pakaian khas kaum lelaki Betawi yang melambangkan kebebasan bergerak dan kesederhanaan.',
    imageUrl: '/assets/wastra-betawi.png',
    coordinates: { lat: -6.2, lng: 106.81 },
  },
  {
    id: 'sunda',
    name: 'Kebaya Sunda',
    origin: 'Jawa Barat',
    description: 'Kebaya Sunda dikenal dengan desainnya yang elegan dan pas di badan, sering dipadukan dengan kain batik corak Sunda.',
    imageUrl: '/assets/wastra-sunda.png',
    coordinates: { lat: -6.91, lng: 107.61 },
  },
  {
    id: 'madura',
    name: 'Pesa\'an Madura',
    origin: 'Jawa Timur',
    description: 'Busana pria Madura dengan kaos bergaris merah-putih dan celana gombrong, melambangkan keberanian dan semangat juang.',
    imageUrl: '/assets/wastra-madura.png',
    coordinates: { lat: -7.0, lng: 113.5 },
  },
  {
    id: 'aceh',
    name: 'Ulee Balang',
    origin: 'Aceh',
    description: 'Pakaian kebesaran bangsawan Aceh, sarat dengan sulaman benang emas yang menunjukkan kemewahan dan status sosial.',
    imageUrl: '/assets/wastra-aceh.png',
    coordinates: { lat: 5.55, lng: 95.32 },
  },
  {
    id: 'lampung',
    name: 'Tulang Bawang',
    origin: 'Lampung',
    description: 'Pakaian adat Lampung yang menggunakan kain tapis, kain tenun khas yang disulam dengan benang emas atau perak.',
    imageUrl: '/assets/wastra-lampung.png',
    coordinates: { lat: -4.55, lng: 105.4 },
  },
  {
    id: 'riau',
    name: 'Teluk Belanga',
    origin: 'Riau',
    description: 'Baju kurung longgar untuk pria dan wanita Melayu, mencerminkan nilai-nilai kesopanan dan keislaman.',
    imageUrl: '/assets/wastra-riau.png',
    coordinates: { lat: 0.5, lng: 101.44 },
  },
  {
    id: 'jambi',
    name: 'Baju Kurung Tanggung',
    origin: 'Jambi',
    description: 'Baju kurung khas Jambi yang panjang lengannya tanggung (tiga perempat), sering dihiasi sulaman emas.',
    imageUrl: '/assets/wastra-jambi.png',
    coordinates: { lat: -1.61, lng: 103.61 },
  },
  {
    id: 'bangkabelitung',
    name: 'Paksian',
    origin: 'Bangka Belitung',
    description: 'Pakaian pengantin wanita yang terinspirasi dari busana Tionghoa, menunjukkan akulturasi budaya di Bangka Belitung.',
    imageUrl: '/assets/wastra-bangkabelitung.png',
    coordinates: { lat: -2.74, lng: 106.44 },
  },
  {
    id: 'banten',
    name: 'Baju Pangsi Banten',
    origin: 'Banten',
    description: 'Pakaian sederhana masyarakat Baduy dan Banten, melambangkan kesahajaan dan kedekatan dengan alam.',
    imageUrl: '/assets/wastra-banten.png',
    coordinates: { lat: -6.4, lng: 106.06 },
  },
  {
    id: 'yogyakarta',
    name: 'Kasatrian Ageng',
    origin: 'Yogyakarta',
    description: 'Busana kebesaran pria di Keraton Yogyakarta, terdiri dari kain batik, surjan, dan blangkon dengan corak khas.',
    imageUrl: '/assets/wastra-yogyakarta.png',
    coordinates: { lat: -7.79, lng: 110.36 },
  },
  {
    id: 'kaltara',
    name: 'Ta\'a & Sapei Sapaq',
    origin: 'Kalimantan Utara',
    description: 'Pakaian wanita (Ta\'a) dan pria (Sapei Sapaq) dari Dayak Kenyah, dihiasi manik-manik dan taring macan.',
    imageUrl: '/assets/wastra-kaltara.png',
    coordinates: { lat: 3.0, lng: 116.0 },
  },
  {
    id: 'gorontalo',
    name: 'Biliu & Makuta',
    origin: 'Gorontalo',
    description: 'Pakaian pengantin Gorontalo (Biliu untuk wanita, Makuta untuk pria) yang sarat dengan hiasan keemasan.',
    imageUrl: '/assets/wastra-gorontalo.png',
    coordinates: { lat: 0.54, lng: 123.05 },
  },
  {
    id: 'sulut',
    name: 'Laku Tepu',
    origin: 'Sulawesi Utara',
    description: 'Pakaian adat dari Sangihe Talaud yang terbuat dari serat tanaman pisang abaka, berbentuk terusan panjang.',
    imageUrl: '/assets/wastra-sulut.png',
    coordinates: { lat: 1.48, lng: 124.84 },
  },
  {
    id: 'sulteng',
    name: 'Baju Nggembe',
    origin: 'Sulawesi Tengah',
    description: 'Baju adat untuk remaja putri Kaili, berbentuk segi empat dengan hiasan manik-manik di bagian leher.',
    imageUrl: '/assets/wastra-sulteng.png',
    coordinates: { lat: -0.9, lng: 119.86 },
  },
  {
    id: 'sulbar',
    name: 'Pattuqduq Towaine',
    origin: 'Sulawesi Barat',
    description: 'Busana penari wanita Mandar, terdiri dari baju kurung, lipa\' saqbe (sarung sutra), dan hiasan kepala yang khas.',
    imageUrl: '/assets/wastra-sulbar.png',
    coordinates: { lat: -2.67, lng: 118.86 },
  },
  {
    id: 'sultra',
    name: 'Babu Nggawi',
    origin: 'Sulawesi Tenggara',
    description: 'Pakaian adat suku Tolaki untuk wanita, terdiri dari blus dan sarung tenun dengan corak gemerlap.',
    imageUrl: '/assets/wastra-sultra.png',
    coordinates: { lat: -3.98, lng: 122.51 },
  },
  {
    id: 'ntb',
    name: 'Baju Lambung',
    origin: 'Nusa Tenggara Barat',
    description: 'Pakaian adat suku Sasak di Lombok, berupa baju hitam tanpa lengan dengan hiasan di bagian dada.',
    imageUrl: '/assets/wastra-ntb.png',
    coordinates: { lat: -8.58, lng: 116.11 },
  },
  {
    id: 'ntt',
    name: 'Pakaian Adat Rote',
    origin: 'Nusa Tenggara Timur',
    description: 'Dikenal dengan topi khas Ti\'i langga untuk pria, dan kain tenun ikat yang kaya motif untuk wanita.',
    imageUrl: '/assets/wastra-ntt.png',
    coordinates: { lat: -10.5, lng: 123.0 },
  },
  {
    id: 'maluku',
    name: 'Baju Cele',
    origin: 'Maluku',
    description: 'Kain kebaya yang dipadukan dengan sarung tenun, memiliki corak kotak-kotak kecil yang khas.',
    imageUrl: '/assets/wastra-maluku.png',
    coordinates: { lat: -3.69, lng: 128.18 },
  },
];
